Ext.define('Devone.devone.shared.com.model.shoppingcontext.FetchCartTotalRMModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "qty",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "subTotal",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "itemId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "img",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stock",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "price",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "productIdDesc",
          "type": "string",
          "defaultValue": ""
     }]
});